---
- name: Import Zabbix GPG key
  ansible.builtin.rpm_key:
    state: present
    key: https://repo.zabbix.com/RPM-GPG-KEY-ZABBIX

- name: Install Zabbix repo
  ansible.builtin.dnf:
    name: "{{ zabbix_repo_url }}"
    state: present

- name: Install Zabbix agent2
  ansible.builtin.dnf:
    name: zabbix-agent2
    state: present

- name: Deploy config file (Jinja2)
  ansible.builtin.template:
    src: zabbix_config.j2
    dest: /etc/zabbix/zabbix_agent2.conf
    owner: root
    group: root
    mode: '0644'
    backup: yes
  notify: Restart Zabbix Agent2

- name: Open firewall port
  ansible.builtin.firewalld:
    port: 10050/tcp
    permanent: yes
    state: enabled
    immediate: yes

- name: Enable and start Zabbix agent2
  ansible.builtin.service:
    name: zabbix-agent2
    state: started
    enabled: yes