[all]
aut-hus01
aut-hus02
aut-hus03

[windowsall]
aut-win01 ansible_host=10.0.0.8

[windowsall:vars]
ansible_user=ansible
ansible_password=Ansible@12345
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_winrm_server_cert_validation=ignore
